翻译第2章任务
ShaBaiTianCN/Proletaria-Expert pull request #18
Opened 2022-05-25 13:34 UTC by nai200

2022-05-25 13:43 UTC, luo-2233 approved these changes, later dismissed

2022-05-25 13:45 UTC, AnzhiZhang requested changes
空格乱了

2022-05-25 13:54 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建阿图姆传送门的信息"
是不是那个手册？

2022-05-25 13:54 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
会不会是表情
https://www.internetslang.com/_3AO)-meaning-definition.asp
```
:O) Definition / :O) Means

The definition of :O) is "Clown nose smiley face"
```

2022-05-25 13:56 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
这里主要是想到了水车，水车不就是转圈圈的吗

2022-05-25 13:56 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
手册？

2022-05-25 13:57 UTC, luo-2233 commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
手册不是P什么的么

2022-05-25 13:58 UTC, luo-2233 commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
It just works翻译过来是"就是这么管用"?

2022-05-25 13:58 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
帕秋莉……

2022-05-25 13:58 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
作者原来的手册不叫这个名字？

2022-05-25 13:59 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
那你这个和O又没啥关系了

2022-05-25 14:00 UTC, luo-2233 commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
前提是建立在那个O是表情的情况下

2022-05-25 14:01 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
我上游戏看看去

2022-05-25 14:02 UTC, luo-2233 commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
作者的书缩写好像是PIP？

2022-05-25 14:02 UTC, luo-2233 commented
确信，approve早了qwq

2022-05-25 14:08 UTC, Cactusstudent commented
> 确信，approve早了qwq

再来张红牌出来（doge）

2022-05-25 14:13 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
> It just works

就这样，它转了

2022-05-25 14:13 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			title: "像O一样运转"
:O 会不会是表示张着嘴的惊叹

2022-05-25 14:37 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/02_technical_progression.snbt
> +			subtitle: "查看BEIB获取搭建它的信息"
书的缩写是PIP

2022-05-25 14:38 UTC, AnzhiZhang commented
> 确信，approve早了qwq

可以view一次选request change

2022-05-26 03:13 UTC, luo-2233 approved these changes

2022-05-26 03:30 UTC, merged