汉化shop任务
ShaBaiTianCN/Proletaria-Expert pull request #24
Opened 2022-05-26 15:07 UTC by luo-2233

Co-authored-by: 2D6 <lir732613@qq.com>

2022-05-26 15:26 UTC, AnzhiZhang requested changes
Plastic中文两个模组是两个译名，是否可以考虑去掉模组名称？

需要对照游戏内检查一遍物品名称

2022-05-26 15:26 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "3x锡碎块"
矿块吧

2022-05-26 15:26 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "3x铁碎块"
同上

2022-05-26 15:26 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "2x塑料片（工业先锋模组）"
```suggestion
			title: "2x塑料片"
```
```suggestion
			title: "2x塑料片（工业先锋）"
```

2022-05-26 15:26 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "2x塑料板（气动工艺模组）"
```suggestion
			title: "2x塑料板"
```
```suggestion
			title: "2x塑料板（气动工艺）"
```

2022-05-26 15:49 UTC, luo-2233 commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "3x锡碎块"
游戏内显示的是矿块

2022-05-26 15:53 UTC, luo-2233 commented
气动工艺与工业先锋的好像都叫塑料片？

2022-05-26 15:54 UTC, luo-2233 commented
![QQ截图20220526235348](https://user-images.githubusercontent.com/104070571/170525736-33bcdc78-58e8-4969-a6e6-89b189e35afa.png)
![QQ截图20220526235335](https://user-images.githubusercontent.com/104070571/170525757-2c2df224-6b75-4abc-b2fb-39ef7d9c9edd.png)

2022-05-27 05:30 UTC, AnzhiZhang requested changes
这类无脑完全使用物品名称的任务名，建议还是打开游戏反而效率高一些

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "3x铜板方块"
![image](https://user-images.githubusercontent.com/37402126/170635011-1d91ab97-6c24-4a37-bc60-488fdfe583d7.png)
```suggestion
			title: "3x铜板金属"
```

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "3x铁板方块"
![image](https://user-images.githubusercontent.com/37402126/170635142-c1bf5f4b-8f27-4c92-99e2-de95948145df.png)
```suggestion
			title: "3x铁板金属"
```

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "2x附魔粉"
![image](https://user-images.githubusercontent.com/37402126/170635214-a8e7fa58-132f-41d0-886c-3f5894b6f7ae.png)
```suggestion
			title: "2x赋魔粉"
```

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "1x岩石切割机"
![image](https://user-images.githubusercontent.com/37402126/170635297-bb031977-cbd6-4e45-8cec-856e65ab0f5c.png)
```suggestion
			title: "1x凿岩机刀片"
```

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "1xHOP石墨粉"
![image](https://user-images.githubusercontent.com/37402126/170635383-4d482075-6293-460e-b354-b8e1f84e889e.png)
```suggestion
			title: "1x高定向热解石墨粉"
```

2022-05-27 05:30 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/shop.snbt
> +			title: "1x血晶球\\&1x黑球体"
& 的显示效果不是很好
![image](https://user-images.githubusercontent.com/37402126/170635566-0752da26-2fa9-4403-8441-23bba3d3bdbe.png)
```suggestion
			title: "1x血晶球 \\& 1x黑球体"
```
```suggestion
			title: "1x血晶球 + 1x黑球体"
```

2022-05-27 06:12 UTC, AnzhiZhang approved these changes
还有一个显示效果问题

2022-05-27 08:26 UTC, merged