汉化植物魔法章节
ShaBaiTianCN/Proletaria-Expert pull request #26
Opened 2022-05-26 15:25 UTC by luo-2233

Co-authored-by: 青金Lapis <lapisqingjin@126.com>

2022-05-26 16:08 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"它可以做旅居者腰带的所有事，甚至。。。更多！O.O"
```suggestion
				"它可以做旅居者腰带的所有事，甚至……更多！O.O"
```

2022-05-26 16:08 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "而且你会不停地走下去。。。"
```suggestion
			subtitle: "而且你会不停地走下去……"
```

2022-05-26 16:08 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "后退。。。"
```suggestion
			subtitle: "后退……"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"虽然提供的护甲值很少，但魔源长袍可以降低所有消耗魔力的装备的魔力消耗。"
```suggestion
				"虽然提供的护甲值很少，但魔源长袍可以减少所有消耗魔力的装备的魔力消耗。"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"套装加成：大幅降低魔力消耗"
```suggestion
				"套装加成：大幅减少魔力消耗"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "太猛男了"
```suggestion
			subtitle: "精致一些"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"它使用魔力值修复自己的耐久值。"
```suggestion
				"它使用魔力修复自己的耐久值。"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"全套属性：略微减少魔力值的消耗、可以给予小精灵额外的药水效果。"
```suggestion
				"全套属性：略微减少魔力的消耗、可以给予小精灵额外的药水效果。"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"全套属性：略微减少魔力值的消耗。"
```suggestion
				"全套属性：略微减少魔力的消耗。"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"全套属性：减少魔力的消耗、即使饥饿值未满时也能回复生命、被动产生魔力值。"
```suggestion
				"全套属性：减少魔力的消耗、即使饥饿值未满时也能回复生命、被动产生魔力。"
```

2022-05-27 08:24 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +				"节制之石会限制激活状态下泰拉粉碎者的挖掘区域为3x3的平面，而不管工具内的魔力值如何。"
```suggestion
				"节制之石会限制激活状态下泰拉粉碎者的挖掘区域为3x3的平面，而不管工具内的魔力如何。"
```

2022-05-27 13:00 UTC, Cactusstudent requested changes
更改部分，但是有些可能不咋样，看着用

2022-05-27 13:00 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["你知道吗，你可以把羊毛套在这些魔力发射器上面，可以让他们更爵士（安静）一点。"]
```suggestion
			description: ["你知道吗？把羊毛套在这些魔力发射器上面，可以让他们更爵士（安静）一点。"]
```
去看了看，挺多的都是这么写的

2022-05-27 13:00 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "远方之地旅行"
```suggestion
			subtitle: "远行之旅"
```
这翻译，妥妥的机翻（虽然可能并不是）

2022-05-27 13:00 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "远方之地旅行"
虽然感觉我这翻译不咋样

2022-05-27 13:00 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "后退……"
```suggestion
			subtitle: "抗住……"
```

2022-05-27 13:07 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			description: ["你知道吗，你可以把羊毛套在这些魔力发射器上面，可以让他们更爵士（安静）一点。"]
改了一下

2022-05-27 13:08 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/botania.snbt
> +			subtitle: "远方之地旅行"
```suggestion
			subtitle: "漫步到远方"
```

2022-05-27 13:12 UTC, merged