第一章翻译
ShaBaiTianCN/Proletaria-Expert pull request #30
Opened 2022-05-27 08:33 UTC by AnzhiZhang

Co-authored-by: 海福 <18917570841@163.com>
Co-authored-by: 北巳 <1321583590@qq.com>

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "ohhh魔力平衡"
```suggestion
			title: "Ahhh魔力平衡"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"欢迎来到&5Proletaria: Expert无产阶级：专家模式."
中文不翻译
```suggestion
				"欢迎来到&5Proletaria: Expert。"
```
```suggestion
				"欢迎来到&5Proletaria: Expert（没有人比我更懂无产阶级）。"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"欢迎来到&5Proletaria: Expert无产阶级：专家模式."
中文不翻译
```suggestion
				"欢迎来到&5Proletaria: Expert。"
```
```suggestion
				"欢迎来到&5Proletaria: Expert（没有人比我更懂无产阶级）。"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"使用整合包提供的&6Proletaria信息手册（PIP）&r 来获取额外的整合包信息以及需要的多方块结构搭建教程，这会自始至终帮助你游玩整合包。"
```suggestion
				"使用整合包提供的&6Proletaria信息手册（PIP）&r来获取额外的整合包信息以及需要的多方块结构搭建教程，这会自始至终帮助你游玩整合包。"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				title: "欢迎游玩"
```suggestion
				title: "欢迎"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
>  					command: "/title @p title {\"text\":\"The Natural Beggings\",\"color\":\"green\"}"
#29
```suggestion
					command: "/title @p title {\"text\":\"自然的起源\",\"color\":\"green\"}"
```

2022-05-27 08:42 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +					title: "第一阶段弹出窗口"
```suggestion
					title: "第一阶段弹窗"
```

2022-05-27 08:55 UTC, AnzhiZhang reviewed
@bilibiliHaifu 留下了几句评论

2022-05-27 08:55 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "一点开花平衡"
@bilibiliHaifu 留了句评论

2022-05-27 08:55 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "Delicate toughness@海福：不知道怎么翻，感觉直译很怪"
@bilibiliHaifu ：不知道怎么翻，感觉直译很怪

2022-05-27 08:55 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "Wood Chucker@海福：chucker机翻是投手，感觉和鹤嘴锄关系不大，不知道怎么翻译"
@bilibiliHaifu ：chucker机翻是投手，感觉和鹤嘴锄关系不大，不知道怎么翻译

2022-05-27 13:51 UTC, Cactusstudent requested changes
问题还有点多，先弄吧

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"按住按键（默认（`），一般位于数字1键左侧）时破坏方块来使用连锁破坏。"
```suggestion
				"按住按键（默认为“`”，一般位于数字1键左侧）时破坏方块来使用连锁破坏。"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"挖局等级："
```suggestion
				"挖掘等级："
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"生产魔力会变得至关重要。你会需要使用原始方法来自动化火红莲或之后更高级的产能花。"
```suggestion
				"生产魔力会变得至关重要，你需要使用更原始的方法来使火红莲或更高级的产能花自动生产魔力。"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +				"你会需要大量活木和活石。你可能会有兴趣多做一些白雏菊，并在不久的将来实现自动化。"
```suggestion
				"你会需要大量活木和活石。多做一些白雏菊或许有好处。不久之后，他们将能实现自动化。"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "活有机物"
```suggestion
			title: "充斥微生物"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "活有机物"
这翻译不算完美，想不出来了

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			description: ["将神秘润滑油和活石或活木输入神秘精炼厂来获取对应方块。"]
这里存疑

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "一点开花平衡"
```suggestion
			title: "一点花之平衡"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "Delicate toughness@海福：不知道怎么翻，感觉直译很怪"
```suggestion
			title: "刚柔并济"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "Wood Chucker@海福：chucker机翻是投手，感觉和鹤嘴锄关系不大，不知道怎么翻译"
```suggestion
			title: "樵夫"
```

2022-05-27 13:51 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "Wood Chucker@海福：chucker机翻是投手，感觉和鹤嘴锄关系不大，不知道怎么翻译"
瞎翻译的，参考

2022-05-28 07:09 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/01_the_natural_beginnings.snbt
> +			title: "活有机物"
```suggestion
			title: "活跃微生物"
```

2022-05-28 07:44 UTC, merged