汉化神秘学章节
ShaBaiTianCN/Proletaria-Expert pull request #39
Opened 2022-05-29 09:30 UTC by luo-2233

Co-authored-by: 咸鱼啊喵丶 <2138208967@qq.com>

2022-05-29 11:48 UTC, AnzhiZhang requested changes

2022-05-29 11:48 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/occultism.snbt
>  			description: ["(psst it works well with ME Network!)"]
1

2022-05-30 04:28 UTC, AnzhiZhang commented on config/ftbquests/quests/chapters/occultism.snbt
>  			description: ["(psst it works well with ME Network!)"]
```suggestion
			description: ["（嘘，它和ME网络共同工作得很好！）"]
```

2022-05-30 12:38 UTC, Cactusstudent commented on config/ftbquests/quests/chapters/occultism.snbt
>  			description: ["(psst it works well with ME Network!)"]
```suggestion
			description: ["(嘘，它和ME网络配合的很好！)"]
```

2022-05-30 12:54 UTC, AnzhiZhang approved these changes

2022-05-30 12:55 UTC, merged