增加zh_cn至L95
ShaBaiTianCN/Proletaria-Expert pull request #41
Opened 2022-06-04 07:20 UTC by Cactusstudent

剩余部分自由接坑

2022-06-04 07:22 UTC, Cactusstudent commented
目前待解决的

- [ ] L1-L95审核
- [ ] L96-L180汉化

2022-06-04 07:23 UTC, Cactusstudent commented
一定要开游戏审核！！！！！！！！！！
一定要开游戏审核！！！！！！！！！！
一定要开游戏审核！！！！！！！！！！
（重要的事情说三遍）

2022-06-04 07:43 UTC, AnzhiZhang requested changes
没加coauthor

2022-06-04 08:41 UTC, AnzhiZhang commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_gamestages.root.title": "Proletaria - 游戏阶段",
为什么加个横线

2022-06-04 08:41 UTC, AnzhiZhang commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_exploration.root.title": "Proletaria - 探索",
为什么加个横线

2022-06-04 08:55 UTC, Cactusstudent commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_exploration.root.title": "Proletaria - 探索",
原因是这属于进度的一个部分，所以我加了“-”但其实不加也没有问题。

2022-06-04 09:01 UTC, Cactusstudent commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_exploration.root.title": "Proletaria - 探索",
> 原因是这属于进度的一个部分，所以我加了“-”但其实不加也没有问题。

![image](https://user-images.githubusercontent.com/97865546/171992384-3926bb69-4012-4d82-89b4-dc3930731c5b.png)
给个图可以参考

2022-06-04 09:03 UTC, Cactusstudent commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_exploration.root.title": "Proletaria - 探索",
所以按我目前的翻译，游戏内应该是 `进度 - Proletaria - 探索`

2022-06-04 11:42 UTC, AnzhiZhang commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_exploration.root.title": "Proletaria - 探索",
```suggestion
  "advancements.proletaria_exploration.root.title": "Proletaria 探索",
```

2022-06-04 11:42 UTC, AnzhiZhang commented on openloader/resources/proletaria/assets/proletaria/lang/zh_cn.json
> +  "advancements.proletaria_gamestages.root.title": "Proletaria - 游戏阶段",
```suggestion
  "advancements.proletaria_gamestages.root.title": "Proletaria 游戏阶段",
```

2022-06-05 15:40 UTC, AnzhiZhang approved these changes

2022-06-05 15:41 UTC, merged